"""adding delivery time

Revision ID: 4cb877807640
Revises: e8b6e6d2d312
Create Date: 2023-06-08 19:53:49.612417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb877807640'
down_revision = 'e8b6e6d2d312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('delivery_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'delivery_time')
    # ### end Alembic commands ###
