"""updating mapped relationship

Revision ID: e8b6e6d2d312
Revises: 4351933f6db0
Create Date: 2023-06-08 16:30:59.353638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b6e6d2d312'
down_revision = '4351933f6db0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
